digitalFoundry:
  sessionId: ""
contentDetection:
  contentCheckInterval: 60000
  maxArchivePage: 1000
automaticDownloads:
  enabled: true
contentManagement:
  scanForExistingFiles: true
  destinationDir: /destination_dir
  workDir: /working_dir
mediaFormats:
  priorities:
    - h.264 (4K)
    - HEVC
    - h.264
    - h.264 (1080p)
    - MP3
downloads:
  maxSimultaneousDownloads: 2
  maxConnectionsPerDownload: 5
  failureRetryIntervalBase: 60000
  maxRetries: 10
postProcessing:
  metadata:
    injectMetadata: true
restApi:
  http:
    port: 44556
logging:
  logLevel: "info"
