#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run update-versions && npm run check-build && npm run update-package-locks && git add */package*.json df-downloader-common/src/df-downloader-version.ts