name: Docker Update

on:
  push:
    branches:
    - main
    - develop
    - experimental

jobs:
  update-dockerhub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract version from package.json
      id: version
      run: |
        VERSION=$(grep -m1 '"version"' package.json | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ vars.DOCKERHUB_USERNAME }}/digital-foundry-downloader:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref == 'refs/heads/develop' && 'development' || 'experimental' }}
          ${{ vars.DOCKERHUB_USERNAME }}/digital-foundry-downloader:v${{ env.VERSION }}${{ github.ref == 'refs/heads/main' && '' || github.ref == 'refs/heads/develop' && '-development' || '-experimental' }}
        labels: |
          version=${{ env.VERSION }}